vexide/pros-rs

.github/workflows/rust.yml
Copied from [`ttyper`](https://github.com/max-niederman/ttyper), except using `cargo check` in lieue of support for `cargo test`.
=> ci: add check, format, and lint jobs

pros-sys/Cargo.toml, pros/Cargo.toml
Bump versions for new pros-rs release
=> bump crate versions

README.md
I fixed grammar in the README file.
=> docs(readme): fix grammar

pros/src/async_runtime/executor.rs, pros/src/async_runtime/mod.rs, pros/src/lib.rs
The async executor now sleeps when there are no futures left for it to poll. 
This stops it from completely starving the OS even when the user has awaited a sleep future.
The `complete_all` function has also been removed because it was broken and could not easily be fixed. 
This has been tested in the simulator and on a real V5 Brain.
=> fix: sleep in async executor when there are no futures left to poll

pros/src/lib.rs, pros/src/time.rs
Adds a microsecond-precision `Instant` reimplementation using `pros::c::micros` internally. Timers are commonly used for many purposes (benchmarking, autonomous routines, etc...). This makes it easier to implement them without juggling around unsafe `pros_sys` system-time related calls.
- Closes #25.
- Most of these methods and docs have been directly dragged over from `std`.
- Currently **untested** on V5 hardware.
=> feat: Reimplement `std::time::Instant`

pros-sys/src/gps.rs, pros/src/sensors/gps.rs
Uses the correct function signature for `gps_set_offset` in the bindings. `gps_set_offset` [returns an i32](https://pros.cs.purdue.edu/v5/api/c/gps.html#gps-set-offset) for throwing error codes, but was treated as a void function in the bindings.
- `GpsSensor::set_offset` now returns a `Result<(), GpsError>` like other setters typically would.
=> fix: `gps_set_offset` function signature

.cargo/config.toml
The flags for building for WASM and the runner for the vexos target are currently outdated. This also fixes the "unwrap on Err in tasks.rs" panic that can sometimes show up in the simulator.
- I have tested these changes in a simulator.
=> fix(cargo): update config for wasm and remove runner

CHANGELOG.md, pros-sys/Cargo.toml, pros/Cargo.toml
Bumps the versions of pros-sys and pros for a new release and updates the changelog.
A new tag (0.6.0) will be created on merge.
These are *only* non-code changes (e.g. documentation, README.md).
=> chore: bump versions and update changelog

CHANGELOG.md, pros/src/sensors/imu.rs
Fixes a clippy warning and adds a `From<Quaternion/Euler> for pros_sys::quaternion/euler_s_t` impl.
- These changes update the crate's interface (e.g. functions/modules added or changed).
=> fix(imu): impl From instead of Into

CHANGELOG.md, packages/pros/src/task/local.rs
This PR makes the task local API more closely resemble `std::thread::LocalKey`. It also resolves a memory leak caused by setting the task-local's value. However, if the task is deleted, there is still a memory leak.
- These are breaking changes (semver: major).
- These changes update the crate's interface (e.g. functions/modules added or changed).
Fixes #31
=> feat(task-local): add cell integration

CHANGELOG.md, packages/pros/examples/battery.rs, packages/pros/src/devices/battery.rs
Closes #50 
- Fixes battery getters to actually handle errors.
- Renames battery getters to correct naming scheme (removes `get_`).
Breaking change (semver:major).
=> refactor(breaking): Battery API

CHANGELOG.md, packages/pros/src/devices/smart/imu.rs
PROS docs incorrectly claim that `imu_get_status` returns PROS_ERR. I assumed this meant PROS_ERR casted to u32, but in reality the flag just returns `E_IMU_STATUS_ERROR`.
- Removed `InertialStatus::error` since that's now reundant.
- Renamed `InertialSensor::is_calibrating` to `InertialSensor::calibrating` to match naming in recent refactors.
- Moved some unsafe blocks around to get nicer formatting.
- Adjusted InertialStatus to implement TryFrom rather than From since that makes more sense in this context.
=> fix(breaking): imu_get_status error handling

packages/pros-sys/src/lib.rs, packages/pros/Cargo.toml, packages/pros/src/io/mod.rs, packages/pros/src/io/print_impl.rs, packages/pros/src/lib.rs
Fixes WASM build errors by using a custom version of libc_print and moving an unsafe function into an unsafe block.
- These are breaking changes (semver: major).
- These changes update the crate's interface (e.g. functions/modules added or changed).
- I have tested these changes in a simulator.
=> fix: resolve wasm build errors

CHANGELOG.md, packages/pros/src/devices/controller.rs
Makes `Controller::status()` return `ControllerError` if one or more of the getter functions it calls fail.
- Untested on actual hardware, but should be better than before either way.
- Closes #71
- This is a breaking change (semver:major).
=> fix: Handle controller status errors

CHANGELOG.md, packages/pros/src/io/mod.rs, packages/pros/src/io/print_impl.rs, packages/pros/src/lib.rs
Removes potentially misleading named-macros from `pros::io`.
- This includes `write`, `ewrite`, `writeln`, and `ewriteln`, which have similarly names to the stuff in `core` and `std`, but do different things.
- Reexports the macros from the `io` module so people can call `pros::io::println` for example.
- Eventually we should refactor `std::io` to use a closer API to `std::stdio` for internals to allow locks on `Stdin` and `Stdout` to write raw strings, but for now this will do.
- Breaking change (semver:major)
=> refactor(breaking): remove nonstandard printing macros

.github/workflows/rust.yml, packages/pros/src/lib.rs, rust-toolchain.toml
This pins the rust toolchain version to prevent things from randomly breaking when rust updates. 
=> fix: pin rust toolchain version

CHANGELOG.md, packages/pros/src/devices/screen.rs
This fixed a panic caused by a faulty check in `screen::draw_buffer` that occurs when the number of pixels the region being drawn to is larger than `u16::MAX`.
=> fix: avoid overflowing multiplications in draw_buffer

CHANGELOG.md, packages/pros/src/lib.rs
As much as we love opcontrol, it shouldn't be the only thing the robot can run.
=> Fix: `AsyncRobot` only runs opcontrol

CHANGELOG.md, packages/pros/src/error.rs
The PROS device registry can set EADDRINUSE in some cases if a device is mismatched or already registered on a port.
Fixes a potential panic (and FPGA reset apparently).
=> fix: handle `EADDRINUSE` in smart port errors

CHANGELOG.md, packages/pros/src/devices/adi/gyro.rs, packages/pros/src/devices/screen.rs, packages/pros/src/devices/smart/imu.rs, packages/pros/src/devices/smart/optical.rs
e.g. `IMU_MIN_DATA_RATE` -> `InertialSensor::MIN_DATA_RATE`. Makes for a cleaner API.
None
=> refactor: move device constants into associated struct `impl`s

CHANGELOG.md, packages/pros-devices/src/adi/encoder.rs
Makes `AdiEncoder` return `Position` rather than just i32 degrees.
Still need to refactor Position to use dynamic TPR amounts.
=> refactor: make `AdiEncoder` return `Position`

CHANGELOG.md, packages/pros-async/src/lib.rs, packages/pros-devices/src/adi/encoder.rs, packages/pros-sync/src/lib.rs
=> fix: disallow unsafe code in robot macros

CHANGELOG.md, packages/pros/src/lib.rs
Adds `Controller` to `pros::prelude` which was missing and pretty commonly used.
=> fix: add `Controller` to prelude

packages/pros-core/src/allocator/mod.rs
This change is a step in updating cargo-pros to use the "none" OS in its target file, which is required to get certain compiler builtins to generate like `fmaxf`.
=> fix: use arch instead of os for allocator

CHANGELOG.md, packages/pros-async/Cargo.toml, packages/pros-core/Cargo.toml, packages/pros-devices/Cargo.toml, packages/pros-panic/Cargo.toml, packages/pros-sync/Cargo.toml, packages/pros-sys/Cargo.toml, packages/pros/Cargo.toml
This pr updates pros-rs to 0.9.0. The, hopefull, final version of pros-rs.
=> chore: bump versions

packages/pros/src/lib.rs
pros-rs is no longer actively maintained, and furthermore, this point was originally inaccurate because PROS is and has always been actively maintained. Therefore, this PR removes references to pros-rs being under active development as an advantage.
- This PR is essentially the same as https://github.com/vexide/vexide/pull/60
=> Remove references to active development

README.md
Directs users to Vexide so they know that there is still development going on, somewhere!
=> docs: direct users to vexide instead
